import {
  add,
  addCircleOutline,
  alertCircleOutline,
  arrowBackOutline,
  arrowForwardOutline,
  bagHandleOutline,
  basketOutline,
  beerOutline,
  bicycleOutline,
  call,
  callOutline,
  cameraOutline,
  carOutline,
  cart,
  cashOutline,
  checkmarkCircleOutline,
  checkmarkDoneCircle,
  chevronBackOutline,
  chevronForwardOutline,
  closeCircle,
  closeOutline,
  cloudUploadOutline,
  documentTextOutline,
  ellipsisVertical,
  eye,
  eyeOff,
  fastFoodOutline,
  helpCircleOutline,
  iceCreamOutline,
  informationCircleOutline,
  listOutline,
  locationOutline,
  lockClosed,
  logOutOutline,
  logoWhatsapp,
  mail,
  mailOutline,
  mapOutline,
  pencil,
  peopleOutline,
  personCircle,
  personCircleOutline,
  personOutline,
  pizzaOutline,
  powerOutline,
  receiptOutline,
  refreshOutline,
  removeCircleOutline,
  restaurantOutline,
  saveOutline,
  search,
  searchCircle,
  settingsOutline,
  shieldCheckmarkOutline,
  statsChartOutline,
  timeOutline,
  trash,
  trashOutline,
  trendingUpOutline,
} from 'ionicons/icons';

export const APP_ICONS = {
  // Interaction
  'checkmark-circle-outline': checkmarkCircleOutline,
  'close-outline': closeOutline,
  'alert-circle-outline': alertCircleOutline,

  // Login
  mail: mail,
  'lock-closed': lockClosed,
  eye: eye,
  'eye-off': eyeOff,

  // Registro de usuario
  'person-circle': personCircle,
  call: call,

  // Home - admin
  'log-out-outline': logOutOutline,
  'person-circle-outline': personCircleOutline,
  'settings-outline': settingsOutline,
  'help-circle-outline': helpCircleOutline,
  'trending-up-outline': trendingUpOutline,
  'stats-chart-outline': statsChartOutline,
  'list-outline': listOutline,
  'people-outline': peopleOutline,

  // Categorías
  'restaurant-outline': restaurantOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'refresh-outline': refreshOutline,
  search: search,
  pencil: pencil,
  trash: trash,
  add: add,
  'save-outline': saveOutline,
  'document-text-outline': documentTextOutline,
  'arrow-back-outline':arrowBackOutline,

  // Productos
  'fast-food-outline': fastFoodOutline,
  'camera-outline': cameraOutline,
  'cloud-upload-outline': cloudUploadOutline,
  'bag-handle-outline': bagHandleOutline,

  // Usuarios
  'person-outline': personOutline,
  'logo-whatsapp': logoWhatsapp,
  'call-outline': callOutline,
  'power-outline': powerOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'information-circle-outline': informationCircleOutline,
  'mail-outline': mailOutline,
  'receipt-outline': receiptOutline,
  'search-outline': searchCircle,

  // Pedidos
  'time-outline': timeOutline,
  'ellipsis-vertical': ellipsisVertical,
  'bicycle-outline': bicycleOutline,
  'checkmark-done-outline': checkmarkDoneCircle,
  'close-circle': closeCircle,
  'map-outline': mapOutline,
  'location-outline': locationOutline,
  'cash-outline': cashOutline,

  // Home - cliente
  'cart-outline': carOutline,
  'pizza-outline': pizzaOutline,
  'beer-outline': beerOutline,
  'ice-cream-outline': iceCreamOutline,
  cart: cart,

  // Carrito
  'trash-outline': trashOutline,
  'add-circle-outline': addCircleOutline,
  'remove-circle-outline': removeCircleOutline,
  'arrow-forward-outline': arrowForwardOutline
};
